### ISSUE TITLE
Notification pop up every time after history cleanup 

### ISSUE THREAD

**Issue by JonseyJones** [madkarmaa/youtube-downloader#10]
Hello!
I set my browser to clean history on exit and every time I reopen it in youtube I get that popup "Welcome version 3..."
I don't care what version it is, I don't want to see any notifications ever, I find it annoying, how can I shut them down forever?

**Comment by madkarmaa** [comment]
since you set your browser to delete your history, there's really nothing you can do other than modifying the code itself. head to lines 38 to 41 in the script:
```js
    let SHOW_NOTIFICATIONS =
        localStorage.getItem('ytdl-notif-enabled') === null
            ? true
            : String(localStorage.getItem('ytdl-notif-enabled')).toLowerCase() === 'true';
```
and change it to:
```js
    let SHOW_NOTIFICATIONS = false;
```
