### ISSUE TITLE
[Feature Request] AV1 Video Support

### ISSUE THREAD

**Issue by SimplyAnotherAnon** [madkarmaa/youtube-downloader#12]
Given that a significant amount of YouTube videos are now being streamed with AV1/Opus as their codecs (open 'stats for nerds' on a supported device), it would be handy if we could download videos in AV1/Opus as a result for a smaller, more efficient file size.

**Comment by madkarmaa** [comment]
open an issue on [Cobalt's repo](https://github.com/wukko/cobalt) since the downloading is made on their side
