### ISSUE TITLE
feat: custom downloader 

### ISSUE THREAD

**Issue by oSumAtrIX** [madkarmaa/youtube-downloader#2]
# Issue

Currently you are restricted to downloading form a certain provider. This creates a dependency to that specific provider to be able to download.

# Solution

Add an option to use a custom downloader. 

# Additional context

In my specific case, I have a downloader for Spotify. I have registered it in Windows to start using a custom protocol. This downloader would be able to launch the protocol and pass in necessary variables such as the title, the channel or the video id.

**Comment by madkarmaa** [comment]
so implement a way to retrieve all the video metadata?

**Comment by madkarmaa** [comment]
such as creating an external API module that retrieves the video metadata

**Comment by oSumAtrIX** [comment]
The downloader part can be abstracted so 

a. You can specify your own downloader API link.
b. You can open a URL with a custom protocol and allow to build the URL using template variables. An example input in the settings of the extension could look like this: `my-downloader://{{videoId}}`. Once you press the Download button it'll replace the template variable with the current video id and open the URL

**Comment by madkarmaa** [comment]
ok, I understand now, but each API could use a different request method and request body. Cobalt, which is the API used in this case, uses a `POST` request with a request body containing the download url and other data

**Comment by oSumAtrIX** [comment]
I'd say you can provide a dropdown of HTTP requests. 

Alternatively you can provide an input area where you can paste your custom handler code and your extension will eval it, like a plugin. Then every case is covered and the possibilities are limitless

**Comment by madkarmaa** [comment]
huge security risk tho, especially `eval()`

**Comment by oSumAtrIX** [comment]
That's intended. The script in the area field is added by the user.

**Comment by madkarmaa** [comment]
I can make a "video API" module to provide them video metadata, then add a settings page with an input for the url, a dropdown for the request type and another input for the request body which gets passed into `JSON.stringify()`, how does that sound to you?

**Comment by oSumAtrIX** [comment]
Personally, I am satisfied as long as I can press the download button and it opens the URL `myprotocol://{{video title}}`. See [why](https://gist.github.com/oSumAtrIX/6abf46e2ea25d32f4e6608c3c3cf837e).

**Comment by madkarmaa** [comment]
this is my current idea, I'll put it in the works

![Picsart_24-01-07_12-11-07-655.png](https://github.com/madkarmaa/youtube-downloader/assets/100418457/ecc1e389-deb2-4de3-b9ff-318a4e11135c)

**Comment by madkarmaa** [comment]
@oSumAtrIX you now have the possibility to write your own code to execute when **left clicking** the download button. placeholders are supported, see a full list [here](https://github.com/madkarmaa/youtube-downloader/blob/main/docs/PLACEHOLDERS.md#currently-supported-placeholder-names)

**Comment by madkarmaa** [comment]
the menu opens by clicking the download button using middle mouse button

![image](https://github.com/madkarmaa/youtube-downloader/assets/100418457/8375ead5-19b3-4354-ae59-50716f6157f8)
