### ISSUE TITLE
Notify popup is not able to close and when the next video autoplay, Auto download (4 downloads) is initiated without download click.

### ISSUE THREAD

**Issue by star777star** [madkarmaa/youtube-downloader#4]
The Script is very good, and the download icon is properly placed and its working good. But the Notify popup is not able to close and it is loaded in the right handside top corner of the browser.

Pl. help, to get the notify popup to close in some internal of time.

![YT Downloader](https://github.com/madkarmaa/youtube-downloader/assets/68146957/300c2926-98f5-4d34-9e28-453a56d5d473)

**Comment by star777star** [comment]
Once the First video is ends and when the next successive video starts auto-play, multiple download is initiated for the current playing video without click on download button.

**Comment by madkarmaa** [comment]
> Once the First video is ends and when the next successive video starts auto-play, multiple download is initiated for the current playing video without click on download button.

I cannot reproduce this issue, please include some steps

**Comment by madkarmaa** [comment]
> The Script is very good, and the download icon is properly placed and its working good. But the Notify popup is not able to close and it is loaded in the right handside top corner of the browser.

I also cannot reproduce this issue, since I can easily access the close button on the top-right corner of the notification

![image](https://github.com/madkarmaa/youtube-downloader/assets/100418457/6a4a8e86-e0b5-474a-b16f-c77d667fd688)

**Comment by star777star** [comment]
HI, Steps below
1) Play a video from the list (this is already loaded after a search). Once the play is clicked (for selected video) or click any other in the list (Right-hand side). The download is initiated by itself with 2 or more download popup for the current playing video.
2) if you click "end" button on the keyboard to end the current video and by auto player will go for the next successive video in 7 secs. And now when the new video is started playing, the download popup initiated again by itself.
3) for the above steps (1 & 2), I have not clicked the download icon in the Player.

![20240410_161831](https://github.com/madkarmaa/youtube-downloader/assets/68146957/193a6717-ee6f-4737-bc78-e5dd7fa28d83)

**Comment by madkarmaa** [comment]
I need information on your browser, browser version, and os, plus a link to said videos list

**Comment by star777star** [comment]
Hi, Pls find below

Browser = Firefox 124.0.2 (64-bit)
OS = Windows 10 Home Single 64 bit (Build 19045) 
Link = https://www.youtube.com/watch?v=cqecyvOs41o

**Comment by madkarmaa** [comment]
update to version 3.0 and see if the issues persist

**Comment by star777star** [comment]
Hi, Tested in few YT, its working good. Hope it will be Green for all.

Thanks, 😊
