### ISSUE TITLE
Download Icon Not Showing in Theatre Mode

### ISSUE THREAD

**Issue by Adish08** [madkarmaa/youtube-downloader#5]
Hello, the icon for downloading is not showing up in the Player when watching a video in Theater Mode, but it works fine in regular mode.

Please consider fixing the issue and making the script work with YouTube's new 2024 UI Update.

Thank you so much for your hard work! I absolutely loved the script!

**Comment by madkarmaa** [comment]
I'm working on a full rewrite :D just wait

**Comment by madkarmaa** [comment]
update to version 3.0 and see if the issues persist

**Comment by Adish08** [comment]
###  Thanks a lot for the update!
 **Everything is working fine now.**
 
  _It would be great to bring back the advanced settings option in the upcoming update._

**Comment by madkarmaa** [comment]
I need to find a more user friendly approach to the advanced download option. any suggestion is appreciated

**Comment by Adish08** [comment]
@madkarmaa Yeah, You can add toggle or Drop-Downs for Advanced Options in the sidebar which appears after pressing P on the keyboard.

**Comment by madkarmaa** [comment]
yeah but they need to be useful
