### ISSUE TITLE
New settings menu opens even while typing in search bar/comments

### ISSUE THREAD

**Issue by squabbled** [madkarmaa/youtube-downloader#6]
When typing in the search, comments, or any other textbox on YouTube, the settings menu opens. This happens when trying to search for videos or write a comment.
![image](https://github.com/madkarmaa/youtube-downloader/assets/40838711/9a98ea50-7df1-4380-9c24-6911e84fb19e)

**Comment by madkarmaa** [comment]
fixed! feel free to re-open the issue if you find any other related problem :)
