### ISSUE TITLE
Notification pops up at random sites without a frame or option to close

### ISSUE THREAD

**Issue by xuintl** [madkarmaa/youtube-downloader#7]
![image](https://github.com/madkarmaa/youtube-downloader/assets/51028862/b6a77d0a-7aae-43e5-ac2f-4aae744111be)

Please see above. Issue seems to appear on websites that have YT frames embedded.

**Comment by madkarmaa** [comment]
please go to line 24 in the script and add the following code:
```js
if (window !== window.parent) return;
```
then tell me if it fixes the issue. I couldn't find any website having YouTube music iframes.

**Comment by xuintl** [comment]
thanks for your reply!

I have unfortunately closed the notification on other pages, so I cannot retest it for the moment.

I will update on here if the issue occurs next time.

good day.

**Comment by madkarmaa** [comment]
don't worry, I created a local page to test and fixed the issue already :)

**Comment by xuintl** [comment]
that's great! I appreciate your promptness. enjoy your weekend
