### ISSUE TITLE
I hoped to set the value at the beginning

### ISSUE THREAD

**Issue by leadra** [madkarmaa/youtube-downloader#8]
原本預想，希望能在腳本開頭設定數值，方便修改
沒有JS基礎，大概是類似圖片，這樣，每次更新腳本後，方便手動修改畫質

Originally, I hoped to set the value at the beginning of the script for easy modification.
There is no JS foundation, it is probably similar to pictures. In this way, it is convenient to manually modify the image quality every time the script is updated.
![image](https://github.com/madkarmaa/youtube-downloader/assets/67009996/9d8c1ec3-c156-4eb9-ae0a-6a7bbbce1c72)

實際實現方式，作者方便就好，只要不增加你的困擾
The implementation method is as long as it is convenient for the author and does not increase your troubles.

**Comment by madkarmaa** [comment]
do you think it should be an advanced option or a regular setting?

**Comment by leadra** [comment]
不好意思，我無法理解術語的意義
是指[預設]?
Sorry, I can't understand the meaning of the term
Does it mean [default]?

**Comment by madkarmaa** [comment]
should it be another option in this list?
![image](https://github.com/madkarmaa/youtube-downloader/assets/100418457/d566ba1b-b415-410c-b7d0-2ddd2b113e25)
or an "advanced option" only when the advanced settings are enabled?
![image](https://github.com/madkarmaa/youtube-downloader/assets/100418457/1f591692-8c18-4f7e-9555-43be05bcddc3)

**Comment by leadra** [comment]
regular setting
It should be more convenient

**Comment by madkarmaa** [comment]
done! :)

![image](https://github.com/madkarmaa/youtube-downloader/assets/100418457/16e93617-fd7b-4ce0-a08c-4531181b7bce)

**Comment by leadra** [comment]
感謝，成功改變畫質並下載了
測試了144p，720p
不過，出現了彈出視窗，不知道是不是晚上網路擁擠的原因
極小機率擋住，不過基本上都可以成功打開api視窗，等約5秒後消失並下載

Thanks, I successfully changed the image quality and downloaded it.
Tested 144p, 720p
However, a pop-up window appeared. I wonder if it is due to network congestion at night.

There is a very small chance of being blocked, but basically the API window can be opened successfully, and it will disappear after about 5 seconds and downloaded.
![image](https://github.com/madkarmaa/youtube-downloader/assets/67009996/6b461518-0d6c-4ca1-8234-ee9101a951a9)
![image](https://github.com/madkarmaa/youtube-downloader/assets/67009996/42d67b5d-90a8-447d-8f66-a83bab0a9edc)

**Comment by madkarmaa** [comment]
that's a blocked popup warning. browsers often block those types of behaviors because they're used to show ads or malicious content. the script uses the `window.open()` method, which gets detected as a potential ad. just allow pop-ups from YouTube and it should be good

**Comment by leadra** [comment]
alright, thank you very much
