### ISSUE TITLE
not working as intended

### ISSUE THREAD

**Issue by Feuer-Kampfer** [madkarmaa/youtube-downloader#9]
When clicking on the download arrow, a new page (blocked.cobalt.tools) opens. It says:

"the website you were on is abusing our free api for their own profit. we blocked them from accessing our servers. this is why you're here.

if you're tired of ads, shady redirects, and also care about your privacy and sanity, switch to the bright side: cobalt.tools

we made cobalt to free you from using websites like the one you were just on. it's also free and open source: github.com/wukko/cobalt

we will redirect you automatically within 20 seconds, or you can just click this link: cobalt.tools"

unable to directly download

**Comment by madkarmaa** [comment]
I've just opened [an issue](https://github.com/imputnet/cobalt/issues/605) to see what the developer of the downloader API has to say

**Comment by madkarmaa** [comment]
it was mistakenly blocked, the developer responded and it's now fixed
